// <auto-generated />
using System;
using AutoMarket.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoMarket.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251230143348_AddAtivoAnuncio")]
    partial class AddAtivoAnuncio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Administrador", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Permissoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("AutoMarket.Models.Anuncio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Ano")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Caixa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Combustivel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Defeito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localizacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModeloId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("Quilometragem")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModeloId");

                    b.HasIndex("VendedorId");

                    b.ToTable("Anuncios");
                });

            modelBuilder.Entity("AutoMarket.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnuncioId")
                        .HasColumnType("int");

                    b.Property<int>("CompradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AnuncioId");

                    b.HasIndex("CompradorId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("AutoMarket.Models.Favorito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnuncioId")
                        .HasColumnType("int");

                    b.Property<int>("CompradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAdicionado")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnuncioId");

                    b.HasIndex("CompradorId");

                    b.ToTable("Favoritos");
                });

            modelBuilder.Entity("AutoMarket.Models.HistoricoAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<int?>("AnuncioAlvoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAcao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UtilizadorAlvoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("AnuncioAlvoId");

                    b.HasIndex("UtilizadorAlvoId");

                    b.ToTable("HistoricosAdmin");
                });

            modelBuilder.Entity("AutoMarket.Models.Imagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnuncioId")
                        .HasColumnType("int");

                    b.Property<int?>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("UrlImagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnuncioId");

                    b.ToTable("Imagens");
                });

            modelBuilder.Entity("AutoMarket.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("AutoMarket.Models.Modelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.ToTable("Modelos");
                });

            modelBuilder.Entity("AutoMarket.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnuncioId")
                        .HasColumnType("int");

                    b.Property<int>("CompradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHoraReserva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PrazoExpiracao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnuncioId");

                    b.HasIndex("CompradorId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("AutoMarket.Models.Utilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivationToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ActivationToken");

                    b.Property<DateTime?>("ActivationTokenExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("ActivationTokenExpiry");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<string>("Contacto")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("Contacto");

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data_registo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("EmailConfirmed");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("FotoUrl");

                    b.Property<string>("Morada")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Morada");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nome");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Password");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PasswordResetToken");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("PasswordResetTokenExpiry");

                    b.Property<bool>("PedidoVendedorPendente")
                        .HasColumnType("bit")
                        .HasColumnName("PedidoVendedorPendente");

                    b.Property<bool>("RejeitadoVendedor")
                        .HasColumnType("bit")
                        .HasColumnName("RejeitadoVendedor");

                    b.Property<string>("TipoUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Tipo_user");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.ToTable("Utilizador");
                });

            modelBuilder.Entity("Bloqueio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataBloqueio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("Bloqueios");
                });

            modelBuilder.Entity("Comprador", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataValidacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Morada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NotificacoesAtivas")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Compradores");
                });

            modelBuilder.Entity("Vendedor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("AdministradorId")
                        .HasColumnType("int");

                    b.Property<int?>("AprovadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Contacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DadosFaturacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Morada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoVendedor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId");

                    b.HasIndex("AprovadoPorId");

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("Administrador", b =>
                {
                    b.HasOne("AutoMarket.Models.Utilizador", "Utilizador")
                        .WithOne("AdministradorInfo")
                        .HasForeignKey("Administrador", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("AutoMarket.Models.Anuncio", b =>
                {
                    b.HasOne("AutoMarket.Models.Modelo", "Modelo")
                        .WithMany("Anuncios")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vendedor", "Vendedor")
                        .WithMany("Anuncios")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Modelo");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("AutoMarket.Models.Compra", b =>
                {
                    b.HasOne("AutoMarket.Models.Anuncio", "Anuncio")
                        .WithMany("Compras")
                        .HasForeignKey("AnuncioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Comprador", "Comprador")
                        .WithMany("Compras")
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anuncio");

                    b.Navigation("Comprador");
                });

            modelBuilder.Entity("AutoMarket.Models.Favorito", b =>
                {
                    b.HasOne("AutoMarket.Models.Anuncio", "Anuncio")
                        .WithMany()
                        .HasForeignKey("AnuncioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comprador", "Comprador")
                        .WithMany("Favoritos")
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anuncio");

                    b.Navigation("Comprador");
                });

            modelBuilder.Entity("AutoMarket.Models.HistoricoAdmin", b =>
                {
                    b.HasOne("Administrador", "Admin")
                        .WithMany("Historicos")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoMarket.Models.Anuncio", "AnuncioAlvo")
                        .WithMany("Historicos")
                        .HasForeignKey("AnuncioAlvoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AutoMarket.Models.Utilizador", "UtilizadorAlvo")
                        .WithMany()
                        .HasForeignKey("UtilizadorAlvoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Admin");

                    b.Navigation("AnuncioAlvo");

                    b.Navigation("UtilizadorAlvo");
                });

            modelBuilder.Entity("AutoMarket.Models.Imagem", b =>
                {
                    b.HasOne("AutoMarket.Models.Anuncio", "Anuncio")
                        .WithMany("Imagens")
                        .HasForeignKey("AnuncioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anuncio");
                });

            modelBuilder.Entity("AutoMarket.Models.Modelo", b =>
                {
                    b.HasOne("AutoMarket.Models.Marca", "Marca")
                        .WithMany("Modelos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("AutoMarket.Models.Reserva", b =>
                {
                    b.HasOne("AutoMarket.Models.Anuncio", "Anuncio")
                        .WithMany("Reservas")
                        .HasForeignKey("AnuncioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Comprador", "Comprador")
                        .WithMany("Reservas")
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anuncio");

                    b.Navigation("Comprador");
                });

            modelBuilder.Entity("Bloqueio", b =>
                {
                    b.HasOne("AutoMarket.Models.Utilizador", "Utilizador")
                        .WithMany("Bloqueios")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("Comprador", b =>
                {
                    b.HasOne("AutoMarket.Models.Utilizador", "Utilizador")
                        .WithOne("CompradorInfo")
                        .HasForeignKey("Comprador", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("Vendedor", b =>
                {
                    b.HasOne("Administrador", null)
                        .WithMany("VendedoresAprovados")
                        .HasForeignKey("AdministradorId");

                    b.HasOne("Administrador", "AprovadoPor")
                        .WithMany()
                        .HasForeignKey("AprovadoPorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AutoMarket.Models.Utilizador", "Utilizador")
                        .WithOne("VendedorInfo")
                        .HasForeignKey("Vendedor", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AprovadoPor");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("Administrador", b =>
                {
                    b.Navigation("Historicos");

                    b.Navigation("VendedoresAprovados");
                });

            modelBuilder.Entity("AutoMarket.Models.Anuncio", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("Historicos");

                    b.Navigation("Imagens");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("AutoMarket.Models.Marca", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("AutoMarket.Models.Modelo", b =>
                {
                    b.Navigation("Anuncios");
                });

            modelBuilder.Entity("AutoMarket.Models.Utilizador", b =>
                {
                    b.Navigation("AdministradorInfo");

                    b.Navigation("Bloqueios");

                    b.Navigation("CompradorInfo");

                    b.Navigation("VendedorInfo");
                });

            modelBuilder.Entity("Comprador", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("Favoritos");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Vendedor", b =>
                {
                    b.Navigation("Anuncios");
                });
#pragma warning restore 612, 618
        }
    }
}
